Initial subject tracking implementation
openmpf/openmpf-python-component-sdk pull request #84
Opened 2024-07-10 17:41 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-09-24 15:42 UTC, jrobble requested changes
> Reviewed 8 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`subject/api/mpf_subject_api/__init__.py` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-O4l47s3-N-5MN4uiWJK:-O4l47s45RI-Ai1c9iCv:bc3zoep) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b5ed27b3073dc4c9f99bbabf5cc0a124d1bb3b34/subject/api/mpf_subject_api/__init__.py#L48)):*
> ```Python
> MediaId = NewType('MediaId', str)
> 
> DetectionComponentType = NewType('DetectionComponentType', str)
> ```

Please provide examples for the `DetectionComponentType` in a comment above this line.
___
*[`subject/examples/PythonSubjectComponent/subject_component/__init__.py` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-O6MJjXg5L1Wsy8AhJrG:-O6MJjXh1jMJLrdiKpxn:bw3nwrr) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b5ed27b3073dc4c9f99bbabf5cc0a124d1bb3b34/subject/examples/PythonSubjectComponent/subject_component/__init__.py#L48)):*
> ```Python
>                 entity = get_single_track_entity(track_id)
>                 entities.append(entity)
>                 relationships.append(get_relationship(entity, detection_job.media_id))
> ```

Please update this to create a relationship between this entity and the one before it. Having a relationship with two entities is more realistic.


<!-- Sent from Reviewable.io -->

2024-10-17 18:51 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2024-12-09 18:06 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`subject/api/mpf_subject_api/__init__.py` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-O4l47s3-N-5MN4uiWJK:-O87pRI1ECRnYM87pYyo:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b5ed27b3073dc4c9f99bbabf5cc0a124d1bb3b34/subject/api/mpf_subject_api/__init__.py#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please provide examples for the `DetectionComponentType` in a comment above this line.
</blockquote></details>

Done.
___
*[`subject/examples/PythonSubjectComponent/subject_component/__init__.py` line 48 at r1](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-O6MJjXg5L1Wsy8AhJrG:-O87vnIMEEpVcNHpXvJf:b-vffkat) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/b5ed27b3073dc4c9f99bbabf5cc0a124d1bb3b34/subject/examples/PythonSubjectComponent/subject_component/__init__.py#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update this to create a relationship between this entity and the one before it. Having a relationship with two entities is more realistic.
</blockquote></details>

That will result in every entity being transitively related to every other. It will also allow entities that are never in the same media to have a relationship. Half the code will exist just to address those issues. That means the component developer needs to figure out which half of the code to ignore. I think having a simple example is better than a realistic example. If a realistic example is required, then the or-tools component is a better example.


<!-- Sent from Reviewable.io -->

2024-12-20 20:49 UTC, jrobble requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`subject/examples/PythonSubjectComponent/subject_component/__init__.py` line 48 at r4](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OEZvsdt8Mx4KTPYw0c2:-OEZvsdt8Mx4KTPYw0c3:b-7gsolu) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/af5a50daa7cc7ff4b1d7b951f31327997953a89a/subject/examples/PythonSubjectComponent/subject_component/__init__.py#L48)):*
> ```Python
>                 entity = get_single_track_entity(track_id)
>                 entities.append(entity)
>                 relationships.append(get_relationship(detection_job.media_id, entity))
> ```

As discussed, please relate each entity back to one other entity. They can all be related to the same one, or hand-picked after the loop. Only important thing is that a relationship has two entities.


<!-- Sent from Reviewable.io -->

2025-01-02 17:58 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`subject/examples/PythonSubjectComponent/subject_component/__init__.py` line 48 at r4](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OEZvsdt8Mx4KTPYw0c2:-OFbqw1L9o5bCGVRYmtr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/af5a50daa7cc7ff4b1d7b951f31327997953a89a/subject/examples/PythonSubjectComponent/subject_component/__init__.py#L48)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, please relate each entity back to one other entity. They can all be related to the same one, or hand-picked after the loop. Only important thing is that a relationship has two entities.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-05 18:34 UTC, jrobble requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`detection/api/mpf_component_api/timing.py` line 53 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OII6qgW0raoSPmo1fdi:-OII6qgW0raoSPmo1fdj:b-e1g8pr) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/c8454328ece5a075b186f6790a41b365111ae42a/detection/api/mpf_component_api/timing.py#L53)):*
> ```Python
> 
> 
> class Timing:
> ```

Why is this part if the API and not the component util?


<!-- Sent from Reviewable.io -->

2025-02-06 12:49 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`detection/api/mpf_component_api/timing.py` line 53 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OII6qgW0raoSPmo1fdi:-OIQI9mg4pQp5_O3cr3u:b-wd5bsg) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/c8454328ece5a075b186f6790a41b365111ae42a/detection/api/mpf_component_api/timing.py#L53)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why is this part if the API and not the component util?
</blockquote></details>

Because it does not rely on any outside libraries. I think we should move everything in component util that does not rely on an external library to the api package. If you agree, I'll create an issue for that.


<!-- Sent from Reviewable.io -->

2025-02-06 18:30 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`detection/api/mpf_component_api/timing.py` line 53 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OII6qgW0raoSPmo1fdi:-OIRWSeR-zUgUwF3h7rE:bm4pbbh) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/c8454328ece5a075b186f6790a41b365111ae42a/detection/api/mpf_component_api/timing.py#L53)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Because it does not rely on any outside libraries. I think we should move everything in component util that does not rely on an external library to the api package. If you agree, I'll create an issue for that.
</blockquote></details>

That makes sense to me. Yes, please create an issue for it.


<!-- Sent from Reviewable.io -->

2025-02-07 14:21 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`detection/api/mpf_component_api/timing.py` line 53 at r5](https://reviewable.io/reviews/openmpf/openmpf-python-component-sdk/84#-OII6qgW0raoSPmo1fdi:-OIVmD_s5AJ-xeM1zLP3:b-c6wjdw) ([raw file](https://github.com/openmpf/openmpf-python-component-sdk/blob/c8454328ece5a075b186f6790a41b365111ae42a/detection/api/mpf_component_api/timing.py#L53)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

That makes sense to me. Yes, please create an issue for it.
</blockquote></details>

This is the issue: https://github.com/openmpf/openmpf/issues/1876


<!-- Sent from Reviewable.io -->

2025-02-10 17:31 UTC, jrobble approved these changes

2025-02-10 17:32 UTC, merged